# Generated by Django 4.0.4 on 2022-05-05 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='Topic',
            new_name='topic',
        ),
    ]
