# Generated by Django 4.0.4 on 2022-05-05 18:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhub', '0002_rename_topic_interest_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='searches',
        ),
        migrations.RemoveField(
            model_name='page',
            name='notes',
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('results', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='webhub.interest')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='webhub.page')),
            ],
        ),
    ]
