# Generated by Django 4.0.4 on 2022-05-06 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhub', '0008_alter_interest_user_alter_note_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='webhub.user'),
        ),
        migrations.AlterField(
            model_name='note',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='webhub.page'),
        ),
        migrations.AlterField(
            model_name='search',
            name='interest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='webhub.interest'),
        ),
    ]
